name: Deploy to EC2

on:
  push:
    branches: [ develop ]   # develop 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build project
      run: ./gradlew build -x test  # CI에서 빌드

    - name: Copy JAR to EC2
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "build/libs/studyhub-backend-0.0.1-SNAPSHOT.jar"
        target: "~/app/studyhub-backend-0.0.1-SNAPSHOT.jar"

    - name: Run deploy script on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/app
          chmod +x ./deploy.sh
          ./deploy.sh